import * as fs from "fs";
import path from "path";
import { PACKAGE_DIR } from "./common.mjs";

const GENERATED_CONTRACT_COMMENT = `
/**
 * This file is autogenerated from Foundry deployment artifacts.
 * You should not edit it manually or your changes might be overwritten.
 */
`;

const DEPLOYMENTS_DIR = path.join(PACKAGE_DIR, "deployments");
const TARGET_FILE = path.join(PACKAGE_DIR, "../nextjs/contracts/deployedContracts.ts");

function getDirectories(dirPath) {
  if (!fs.existsSync(dirPath)) {
    return [];
  }

  return fs
    .readdirSync(dirPath, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);
}

function getContractNames(dirPath) {
  return fs
    .readdirSync(dirPath, { withFileTypes: true })
    .filter(dirent => dirent.isFile() && dirent.name.endsWith(".json"))
    .map(dirent => dirent.name.replace(/\.json$/, ""));
}

function getInheritedFunctions(metadata, contractName) {
  if (!metadata?.sources) {
    return {};
  }

  for (const [sourcePath, source] of Object.entries(metadata.sources)) {
    const sourceName = sourcePath.split("/").pop()?.replace(/\.sol$/, "");
    if (sourceName !== contractName || typeof source.content !== "string") {
      continue;
    }

    const match = source.content.match(/contract\s+\w+\s+is\s+([^{}]+)\{/);
    if (!match) {
      return {};
    }

    return match[1]
      .split(",")
      .map(name => name.trim())
      .reduce((acc, inheritedContract) => ({ ...acc, [inheritedContract]: sourcePath }), {});
  }

  return {};
}

function getContractDataFromDeployments() {
  const output = {};

  for (const chainName of getDirectories(DEPLOYMENTS_DIR)) {
    const chainDir = path.join(DEPLOYMENTS_DIR, chainName);
    const chainId = fs.readFileSync(path.join(chainDir, ".chainId"), "utf8").trim();
    const contracts = {};

    for (const contractName of getContractNames(chainDir)) {
      const contractJson = JSON.parse(fs.readFileSync(path.join(chainDir, `${contractName}.json`), "utf8"));
      const metadata = contractJson.metadata
        ? typeof contractJson.metadata === "string"
          ? JSON.parse(contractJson.metadata)
          : contractJson.metadata
        : undefined;

      contracts[contractName] = {
        address: contractJson.address,
        abi: contractJson.abi,
        inheritedFunctions: getInheritedFunctions(metadata, contractName),
        deployedOnBlock: contractJson.receipt?.blockNumber,
      };
    }

    output[chainId] = contracts;
  }

  return output;
}

async function main() {
  const allContractsData = getContractDataFromDeployments();
  const fileContent = Object.entries(allContractsData).reduce(
    (content, [chainId, chainConfig]) => `${content}${Number.parseInt(chainId, 10)}:${JSON.stringify(chainConfig, null, 2)},`,
    "",
  );

  const output = `${GENERATED_CONTRACT_COMMENT}import type { ContractsDeclaration } from "~~/contracts/types";

const deployedContracts = {${fileContent}} as const;

export default deployedContracts satisfies ContractsDeclaration;
`;

  fs.writeFileSync(TARGET_FILE, output);

  console.log(`Updated ${TARGET_FILE}`);
}

main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
