[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
fs_permissions = [
  { access = "read", path = "./broadcast" },
  { access = "read", path = "./out" },
  { access = "read-write", path = "./deployments" },
  { access = "read-write", path = "../nextjs/contracts" },
]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
mainnet = "https://mainnet.rpc.buidlguidl.com"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrumSepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimismSepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonAmoy = "https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonZkEvm = "https://polygonzkevm-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonZkEvmCardona = "https://polygonzkevm-cardona.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
gnosis = "https://rpc.gnosischain.com"
chiado = "https://rpc.chiadochain.net"
base = "https://mainnet.base.org"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
scrollSepolia = "https://sepolia-rpc.scroll.io"
scroll = "https://rpc.scroll.io"
celo = "https://forno.celo.org"
celoSepolia = "https://forno.celo-sepolia.celo-testnet.org/"

[etherscan]
mainnet = { key = "${ETHERSCAN_V2_API_KEY}" }
sepolia = { key = "${ETHERSCAN_V2_API_KEY}" }
base = { key = "${ETHERSCAN_V2_API_KEY}" }
baseSepolia = { key = "${ETHERSCAN_V2_API_KEY}" }
